#  The following commands are available:
#  - all-Resource                          : runs terraform plan for an environment
#  - specific-global-Resource              : runs terraform apply for an environment
#  - specific-regional-Resource            : runs terraform apply for an environment
# Folder directory structure
# .
# ├── Terraform
# │   └── env
# │       ├── global
# │       │   ├── tfstate-gcs
# │       │   └── vpc_subnets
# │       └── region
# │           └── asia-south1
# │               └── gke


steps:
  - name: 'gcr.io/souviks-world/gcloud-terraform:latest'  #create this docker image using a Dockerfile
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |
        make specific-regional-Resource dir-name gke
    id: Create the terraform resources


logsBucket: 'gs://gcp-cloud-build-logs'
options:
  logging: GCS_ONLY
timeout: 86400s
