#  The following commands are available:
#  - all-Resource                          : runs terraform plan for an environment
#  - specific-global-Resource              : runs terraform apply for an environment
#  - specific-regional-Resource            : runs terraform apply for an environment
# Folder directory structure
# .
# └── Terraform
#     └── env
#         ├── global
#         │   ├── tfstate-gcs
#         │   └── vpc_subnets
#         └── region
#             └── asia-south1
#                 └── gke

steps:
  - name: 'hashicorp/terraform:1.0.4'
    args:
      - '-c'
      - |
        make all-Resource
    id: Create all the terraform resources

logsBucket: 'gs://souvik-jenkins-bucket'
options:
  logging: GCS_ONLY
timeout: 86400s
