#  The following commands are available :
#  - all-resource                          : Make will create all the terraform resources.
#  - specific-global-resource              : Make will create the specific global resources.
#  - specific-regional-resource            : Make will reate the specific regional resources
#  - Folder directory structure            :
                                            # .
                                            # └── Terraform
                                            #     └── env
                                            #         ├── global
                                            #         │   ├── tfstate-gcs
                                            #         │   └── vpc_subnets
                                            #         └── region
                                            #             └── asia-south1
                                            #                 └── gke

steps:
  - name: 'gcr.io/souviks-world/gcloud-terraform:latest'
    id: Create the terraform resources
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |
        make specific-regional-resource dir_name=gke

logsBucket: 'gs://gcp-cloud-build-logs'
options:
  logging: GCS_ONLY
timeout: 86400s