steps:
  - name: 'gcr.io/searce-playground-v1/gcloud-terraform:latest'
    id: VPN deployment
    entrypoint: 'bash'
    dir: vpn-privatepool
    args: ['./vpn-script.sh']

  - name: 'gcr.io/searce-playground-v1/gcloud-terraform:latest'
    id: Workerpool deployment
    entrypoint: 'bash'
    dir: vpn-privatepool
    args: ['./pool-script.sh']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'builds', 'triggers', 'run', 'deployment', '--branch=main']
    id: 'trigger next build'

logsBucket: 'gs://logs-cloudbuild'
options:
  logging: GCS_ONLY
timeout: 86400s
